#see: https://godatadriven.com/blog/a-practical-guide-to-setuptools-and-pyproject-toml/
# using the 'src/ layout'
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
